### ISSUE TITLE
Lunar isnt launching

### ISSUE THREAD

**Issue by SoulFire2879** [Aetopia/Lunar-Client-Mini#2]
i deleted lunar client, downloaded this one, installed it thought this launcher, clicked launch and nothing happens

**Comment by SoulFire2879** [comment]
Was a mistake ,sorry

**Comment by SoulFire2879** [comment]
https://user-images.githubusercontent.com/77575770/145672350-72de6ce2-1cfb-4d68-9284-517c45eb4526.mp4

Video please watch i think its the newest lunar updates . https://github.com/Aetopia/LCLPy also stopped working after the latest updates which added snaplook , hypixel quickplay and others

**Comment by Aetopia** [comment]
LC Portable uses it own Lunar Client Installation, ever tried to click on Install/Update?

**Comment by SoulFire2879** [comment]
> LC Portable uses it own Lunar Client Installation, ever tried to click on Install/Update?

I did , i downloaded it, clicked the install/update button, opened cmd and did a bunch of stuff, then powershell opened, and it closed and i got a message box saying successfully installed or something and i clicked launch and nothing happens

**Comment by Aetopia** [comment]
why the heck is your memory at 72 percent?

**Comment by SoulFire2879** [comment]
> why the heck is your memory at 72 percent?

I have a trash pc lmao 
can you help me fix my issue lol

**Comment by SoulFire2879** [comment]
Please help

**Comment by Aetopia** [comment]
lunar jar files aren't even downloaded my friend.....

**Comment by SoulFire2879** [comment]
> lunar jar files aren't even downloaded my friend.....

i told you, i deleted the default lunar launcher and every file of lunar using (clean uninstall) and then i downloaded this one, clicked install / update, did a lot of stuff and i clicked launch and nothing happens whyy
